### ISSUE TITLE
Schema invalid due to API update (equipment_pvp)

### ISSUE THREAD

**Issue by Xyaren** [gw2efficiency/api-status#19]
Due to the recent api update (https://api.guildwars2.com/v2.json?v=latest) the schema for `/v2/characters/:id ` is no longer valid.
`equipment_pvp` moved into `equipment_tabs`.
### Change:
```
  v: "2021-04-06T21:00:00.000Z",
  desc: "Remove `equipment_pvp` and add `equipment_tabs_pvp` for `/v2/characters/:id`"
```

### Example:
https://api.guildwars2.com/v2/characters?page=0&page_size=200&v=latest&access_token=564F181A-F0FC-114A-A55D-3C1DCD45F3767AF3848F-AB29-4EBF-9594-F91E6A75E015&lang=en

### Error:
```
'data.0.equipment_pvp' is required
'data.1.equipment_pvp' is required
```
### This is how it looks now
![image](https://user-images.githubusercontent.com/5864045/113841405-f3b96e00-9791-11eb-82be-02a31341238c.png)

**Comment by queicherius** [comment]
Thanks for reporting, should be fixed now :)
